CREATE TABLE NEWS_SENTIMENT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STOCK_CODE VARCHAR2(20) NOT NULL,
    NEWS_TITLE VARCHAR2(1000),
    SENTIMENT_SCORE NUMBER DEFAULT 50,
    SENTIMENT_REASON VARCHAR2(2000),
    SOURCE_URL VARCHAR2(2000),
    PUBLISHED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_NEWS_URL UNIQUE (SOURCE_URL)
);

CREATE INDEX IDX_NEWS_SENTIMENT_CODE ON NEWS_SENTIMENT(STOCK_CODE);
CREATE INDEX IDX_NEWS_SENTIMENT_DATE ON NEWS_SENTIMENT(PUBLISHED_AT DESC);

